### ISSUE TITLE
proper format for search bar 

### ISSUE THREAD

**Issue by alkock** [giomf/ff-eppendorf-website#7]
<img width="605" alt="image" src="https://github.com/giomf/ff-eppendorf-website/assets/18499444/e9f74f35-4331-4fc4-8118-9276e286fc03">

The size of the search-bar does not fit the text inside.

**Comment by giomf** [comment]
I can reproduce this only on very small screens. Is this picture from your phone?
Unfortunately this is handled by our hugo theme and right now its seams that I dont have the option changing this.

**Comment by alkock** [comment]
No the website was opened on a MacBook 13" (macOS Sonoma) on Google Chrome Version 118.0.5993.117 (Official Build) (arm64) & res: 1440x900px

**Comment by giomf** [comment]
Cannot reproduce it in firefox and chrome.
Reopen it so we can tackle this later.

**Comment by giomf** [comment]
Could you check if this is still a problem?

**Comment by alkock** [comment]
![image](https://github.com/giomf/ff-eppendorf-website/assets/18499444/27547f63-8bcf-499e-b8e6-3c9e0f88788b)

Yes, this problem still present.

**Comment by alkock** [comment]
<img width="1417" alt="image" src="https://github.com/giomf/ff-eppendorf-website/assets/18499444/19a75250-1151-4e81-814d-fffc18ceae76">

**Comment by alkock** [comment]
I will have a look on this. @giomf

**Comment by alkock** [comment]
<img width="498" alt="Screenshot 2024-04-11 at 10 56 39" src="https://github.com/giomf/ff-eppendorf-website/assets/18499444/ed9b94c1-5044-4b24-8051-f2cb1c1c68c3">

adding the width-attribute to the css .ms-md-3 you can change in any constellation the search bar to be shown properly. 
I have no clue where to add this to your settings of hugo :/

**Comment by giomf** [comment]
I thought a bit about it and I think the best  way to tackle this is to open a issue on the hinode [repo](https://github.com/gethinode/hinode) because it seams to be related to our theme and only certain platforms are affected.
Could you do this?

**Comment by alkock** [comment]
surley, I will do this :)

**Comment by giomf** [comment]
Ive bumped versions in #74 so that the fix for this should be included. Could you check again please?

**Comment by alkock** [comment]
fixed.
