### ISSUE TITLE
Proper logo display

### ISSUE THREAD

**Issue by alkock** [giomf/ff-eppendorf-website#74]
Since a update there seems to be something wrong with the upper logo:

<img width="472" alt="image" src="https://github.com/giomf/ff-eppendorf-website/assets/18499444/a2b349fb-b098-4725-a7d5-af99d0c658b2">

**Comment by giomf** [comment]
Damn... Yes i can reproduce it at on mobile.

**Comment by alkock** [comment]
@giomf Desktop and mobile.

**Comment by giomf** [comment]
@alkock Please check again. The issue is solved for me with the last release.

**Comment by giomf** [comment]
@alkock Is it still an issue for you?

**Comment by alkock** [comment]
lgtm
